---
- name: Check for the hosts of the OpenStack cloud
  os_server_facts:
    cloud: openstack
    server: *
    filters:
      deployment_name: QA
- debug:
    var: group

- name: Destroy all the environment created on QA after a failing error
  os_server_group:
    state: absent
    name: group

# tasks file for roles/osp-instance-delete
