---
- name: Collect info from Openstack servers and use inmemory inventory to install Multi-tier app
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Gather information from Openstack hosts
      os_server_info:
        cloud: openstack
        server: front*
      register: result
    - name: Add the host to inmemory
      add_host:
        hostname: "{{ item.accessIPv4 }}"
        groups: "{{ item.metadata.group }}"
      loop: "{{ result.openstack_servers }}"

#having problems with the variable to be readed by Tower, trying to store it
    - name: Store the variable
      set_fact:
        smoke_ip: "{{ result.hostname }}"
    - name: Check webservers
#      host: "{{ smoke_ip }}"
      uri:
        url: "http://{{ item.smoke_ip }}"
        return_content: yes
      until: '"alive" in webpage.content'
      retries: 10
      delay: 1
      register: webpage
      loop: "{{ smoke_ip }}"
      delegate_to: localhost
    
    - name: Fail if 'Ansible has done its job' is not in the page content
      fail:
      when: "'Ansible has done its job' not in webpage.results[0].content"
#      tags:
#        - osp.smoke
