---
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: result
- name: Add host
  add_host:
    name: "{{ item.name }}"
    group: "{{ item.metadata.group }}"
  with_items: "{{result.openstack_servers}}"
